# Generated by Django 4.2 on 2025-08-21 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='类别名称')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL别名')),
                ('description', models.TextField(blank=True, verbose_name='类别描述')),
                ('image', models.ImageField(blank=True, upload_to='categories/', verbose_name='类别图片')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '零食类别',
                'verbose_name_plural': '零食类别',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='产品名称')),
                ('slug', models.SlugField(max_length=200, unique_for_date='created_at', verbose_name='URL别名')),
                ('image', models.ImageField(blank=True, upload_to='products/', verbose_name='产品图片')),
                ('description', models.TextField(blank=True, verbose_name='产品描述')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('stock', models.PositiveIntegerField(verbose_name='库存数量')),
                ('available', models.BooleanField(default=True, verbose_name='是否上架')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='所属类别')),
            ],
            options={
                'verbose_name': '零食产品',
                'verbose_name_plural': '零食产品',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['id', 'slug'], name='products_pr_id_a08e3c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='products_pr_name_9ff0a3_idx'),
        ),
    ]
